package forms;
import java.awt.Color;
import java.awt.Font;
import javax.swing.*;
import java.sql.*;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
public class MTechAvg extends JFrame
{
 JLabel l1,l2,l3,l4,l5,l6,l7,l8,l9,l10;
 JTextField t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14,t15,t16;
 Font f;
 float gcse,git,gece,geee,gma,ocse,oit,oece,oeee,oma,scse,sit,sece,seee,sma;
 float avg,max,diff;
 private Connection con;
 private PreparedStatement ps1;
 private ResultSet rs1;
 public MTechAvg(String title)
 {
     super(title);
     f=new Font("Arial",Font.BOLD,18);
  l1=new JLabel("C.S.E");
  l2=new JLabel("I.T");
  l3=new JLabel("E.C.E");
  l4=new JLabel("Average");
  l5=new JLabel("E.E.E");
  l6=new JLabel("M.A.E");
  l7=new JLabel("General");
  l8=new JLabel("O.B.C");
  l9=new JLabel("SC/ST");
  l10=new JLabel("M.Tech");
  t1=new JTextField();
  t2=new JTextField();
  t3=new JTextField();
  t4=new JTextField();
  t5=new JTextField();
  t6=new JTextField();
  t7=new JTextField();
  t8=new JTextField();
  t9=new JTextField();
  t10=new JTextField();
  t11=new JTextField();
  t12=new JTextField();
  t13=new JTextField();
  t14=new JTextField();
  t15=new JTextField();
  t16=new JTextField();
  setLayout(null);
  l1.setBounds(10,50,100,30);
  l10.setBounds(10, 10, 100, 30);
  add(l10);
  l10.setFont(f);
  l10.setForeground(Color.blue);
  t1.setBounds(120,50,80,30);
  l2.setBounds(10,90,100,30);
  t2.setBounds(120,90,80,30);
  l3.setBounds(10,130,100,30); 
  t3.setBounds(120,130,80,30);
  l4.setBounds(150,280,100,30);
  t4.setBounds(250,280,80,30);
  l5.setBounds(10,170,100,30);
  t5.setBounds(120,170,80,30);
  l6.setBounds(10,210,100,30);
  t6.setBounds(120,210,80,30);
  l7.setBounds(130,5,100,30);
  l8.setBounds(280,5,100,30);
  l9.setBounds(430,5,100,30);
  t7.setBounds(270,50,80,30);
  t8.setBounds(270,90,80,30);
  t9.setBounds(270,130,80,30);
  t10.setBounds(270,170,80,30);
  t11.setBounds(270,210,80,30);
  t12.setBounds(420,50,80,30);
  t13.setBounds(420,90,80,30);
  t14.setBounds(420,130,80,30);
  t15.setBounds(420,170,80,30);
  t16.setBounds(420,210,80,30);
  l1.setFont(f);
  l2.setFont(f);
  l3.setFont(f);
  l4.setFont(f);
  l5.setFont(f);
  l6.setFont(f);
  l7.setFont(f);
  l7.setForeground(Color.blue);
  l8.setFont(f);
  l8.setForeground(Color.blue);
  l9.setFont(f);
  l9.setForeground(Color.blue);
 add(l1);add(t1);
 add(l2);add(t2);
 add(l3);add(t3);
 add(l4);add(t4);
 add(l5);add(t5);
 add(l6);add(t6);
 add(l7);add(l8);
 add(l9);add(t7);
 add(t8);add(t9);
 add(t10);add(t11);
 add(t12);add(t13);
 add(t14);add(t15);
 add(t16);
     try 
     {
         Database db=new Database();
         con=db.connect();
         ps1=con.prepareStatement("select avg(gpa),max(gpa) from mav where ccat='General'");
         rs1=ps1.executeQuery();
         rs1.next();
         avg=rs1.getFloat("avg(gpa)");
         max=rs1.getFloat("max(gpa)");
         String avgs=Float.toString(avg);
         t4.setText(avgs);
         diff=max-avg;
         gcse=avg+diff;
         String s1=Float.toString(gcse);
         t1.setText(s1);
         git=avg+(diff/2);
         String s2=Float.toString(git);
         t2.setText(s2);
         gece=avg-(diff/2);
         String s3=Float.toString(gece);
         t3.setText(s3);
         geee=avg-diff;
         String s4=Float.toString(geee);
         t5.setText(s4);
         gma=avg-(2*diff);
         String s5=Float.toString(gma);
         t6.setText(s5);
         ocse=git;
         oit=gece;
         oece=geee;
         oeee=gma;
         oma=oeee-diff;
         scse=oece;
         sit=oeee;
         sece=oma;
         seee=sece-(diff/2);
         sma=sece-diff;
         String s6=Float.toString(ocse);
         t7.setText(s6);
         String s7=Float.toString(oit);
         t8.setText(s7);
         String s8=Float.toString(oece);
         t9.setText(s8);
         String s9=Float.toString(oeee);
         t10.setText(s9);
         String s10=Float.toString(oma);
         t11.setText(s10);
         String s11=Float.toString(scse);
         t12.setText(s11);
         String s12=Float.toString(sit);
         t13.setText(s12);
         String s13=Float.toString(sece);
         t14.setText(s13);
         String s14=Float.toString(seee);
         t15.setText(s14);
         String s15=Float.toString(sma);
         t16.setText(s15);
         t1.setEditable(false);t1.setBackground(Color.white);
         t2.setEditable(false);t2.setBackground(Color.white);
         t3.setEditable(false);t3.setBackground(Color.white);
         t4.setEditable(false);t4.setBackground(Color.white);
         t5.setEditable(false);t5.setBackground(Color.white);
         t6.setEditable(false);t6.setBackground(Color.white);
         t7.setEditable(false);t7.setBackground(Color.white);
         t8.setEditable(false);t8.setBackground(Color.white);
         t9.setEditable(false);t9.setBackground(Color.white);
         t10.setEditable(false);t10.setBackground(Color.white);
         t11.setEditable(false);t11.setBackground(Color.white);
         t12.setEditable(false);t12.setBackground(Color.white);
         t13.setEditable(false);t13.setBackground(Color.white);
         t14.setEditable(false);t14.setBackground(Color.white);
         t15.setEditable(false);t15.setBackground(Color.white);
         t16.setEditable(false);t16.setBackground(Color.white);
     } catch (Exception e) 
     {
         e.printStackTrace();
     }
 }public static void main(String[] args)
    {
      MTechAvg obj=new MTechAvg("MTech. Show Average");  
        obj.setSize(600,400);
        obj.setLocation(250,200);
        obj.setDefaultCloseOperation(EXIT_ON_CLOSE);
        obj.setVisible(true);
    }
 
}
